// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using back_end_for_TMS.Infrastructure.Database;

#nullable disable

namespace back_end_for_TMS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260329105214_Base")]
    partial class Base
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "r-admin",
                            ConcurrencyStamp = "STATIC_STAMP_123456",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "r-user",
                            ConcurrencyStamp = "STATIC_STAMP_123456",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "u-admin",
                            RoleId = "r-admin"
                        },
                        new
                        {
                            UserId = "u-user1",
                            RoleId = "r-user"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("back_end_for_TMS.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AppName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("TenantId");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "u-admin",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "STATIC_STAMP_123456",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@asp.app",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ASP.APP",
                            NormalizedUserName = "TOP1SERVER",
                            PasswordHash = "AQAAAAIAAYagAAAAEOf6Pb8v/8VwLIDv8T6/7UfVvJqR9Z0X5Y6vX5Y6vX",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "STATIC_STAMP_123456",
                            TenantId = new Guid("0195c63a-727b-7f32-8e2d-3f4a5b6c7d8e"),
                            TwoFactorEnabled = false,
                            UserName = "Top1Server"
                        },
                        new
                        {
                            Id = "u-user1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "STATIC_STAMP_123456",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user1@asp.app",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER1@ASP.APP",
                            NormalizedUserName = "USER1",
                            PasswordHash = "AQAAAAIAAYagAAAAEOf6Pb8v/8VwLIDv8T6/7UfVvJqR9Z0X5Y6vX5Y6vX",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "STATIC_STAMP_123456",
                            TenantId = new Guid("0195c63a-727b-7f32-8e2d-3f4a5b6c7d8e"),
                            TwoFactorEnabled = false,
                            UserName = "User1"
                        });
                });

            modelBuilder.Entity("back_end_for_TMS.Models.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CustomerType")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("CustomerId");

                    b.HasIndex("TenantId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = new Guid("0195d004-cccc-7000-8000-000000000001"),
                            Address = "123 Nguyễn Huệ, Quận 1, Tp. Hồ Chí Minh",
                            ContactPerson = "Nguyễn Văn Toàn",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerType = 2,
                            Email = "info@thuanphat.vn",
                            Name = "Công ty TNHH Thuận Phát",
                            PhoneNumber = "0281234567",
                            Status = 1,
                            TaxCode = "0312345678",
                            TenantId = new Guid("0195c63a-727b-7f32-8e2d-3f4a5b6c7d8e")
                        },
                        new
                        {
                            CustomerId = new Guid("0195d004-cccc-7000-8000-000000000002"),
                            Address = "456 Lê Lợi, Quận 3, Tp. Hồ Chí Minh",
                            ContactPerson = "Trần Thị Hoa",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerType = 2,
                            Email = "contact@namviet.com.vn",
                            Name = "Công ty CP Nam Việt",
                            PhoneNumber = "0282345678",
                            Status = 1,
                            TaxCode = "0323456789",
                            TenantId = new Guid("0195c63a-727b-7f32-8e2d-3f4a5b6c7d8e")
                        },
                        new
                        {
                            CustomerId = new Guid("0195d004-cccc-7000-8000-000000000003"),
                            Address = "789 Trần Hưng Đạo, Quận 5, Tp. Hồ Chí Minh",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerType = 1,
                            Name = "Nguyễn Minh Khoa",
                            PhoneNumber = "0903456789",
                            Status = 1,
                            TenantId = new Guid("0195c63a-727b-7f32-8e2d-3f4a5b6c7d8e")
                        },
                        new
                        {
                            CustomerId = new Guid("0195d004-cccc-7000-8000-000000000004"),
                            Address = "12 Đinh Tiên Hoàng, Bình Thạnh, Tp. Hồ Chí Minh",
                            ContactPerson = "Lê Văn Hưng",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerType = 2,
                            Email = "hungthinhlogistics@gmail.com",
                            Name = "Doanh nghiệp Tư nhân Hưng Thịnh",
                            PhoneNumber = "0284567890",
                            Status = 1,
                            TaxCode = "0334567890",
                            TenantId = new Guid("0195c63a-727b-7f32-8e2d-3f4a5b6c7d8e")
                        },
                        new
                        {
                            CustomerId = new Guid("0195d004-cccc-7000-8000-000000000005"),
                            Address = "34 Võ Văn Tần, Quận 3, Tp. Hồ Chí Minh",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerType = 1,
                            Email = "lethu@gmail.com",
                            Name = "Lê Thị Thu",
                            PhoneNumber = "0905678901",
                            Status = 1,
                            TenantId = new Guid("0195c63a-727b-7f32-8e2d-3f4a5b6c7d8e")
                        },
                        new
                        {
                            CustomerId = new Guid("0195d004-cccc-7000-8000-000000000006"),
                            Address = "78 Lý Tự Trọng, Quận 1, Tp. Hồ Chí Minh",
                            ContactPerson = "Phạm Quốc Hải",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerType = 2,
                            Email = "hailong.transport@vnn.vn",
                            Name = "Công ty TNHH Hải Long",
                            Notes = "Khách hàng tạm dừng hợp đồng",
                            PhoneNumber = "0286789012",
                            Status = 2,
                            TaxCode = "0356789012",
                            TenantId = new Guid("0195c63a-727b-7f32-8e2d-3f4a5b6c7d8e"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            CustomerId = new Guid("0195d004-cccc-7000-8000-000000000007"),
                            Address = "90 Lê Văn Việt, Quận 9, Tp. Hồ Chí Minh",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerType = 1,
                            Name = "Phạm Văn Dũng",
                            PhoneNumber = "0907890123",
                            Status = 1,
                            TenantId = new Guid("0195c63a-727b-7f32-8e2d-3f4a5b6c7d8e")
                        },
                        new
                        {
                            CustomerId = new Guid("0195d004-cccc-7000-8000-000000000008"),
                            Address = "44 Hai Bà Trưng, Quận 1, Tp. Hồ Chí Minh",
                            ContactPerson = "Hoàng Thị Lan",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerType = 2,
                            Email = "vietmy.co@gmail.com",
                            Name = "Công ty CP Việt Mỹ",
                            PhoneNumber = "0288901234",
                            Status = 1,
                            TaxCode = "0378901234",
                            TenantId = new Guid("0195c63a-727b-7f32-8e2d-3f4a5b6c7d8e")
                        });
                });

            modelBuilder.Entity("back_end_for_TMS.Models.Driver", b =>
                {
                    b.Property<Guid>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenseClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LicenseExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("DriverId");

                    b.HasIndex("TenantId");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            DriverId = new Guid("0195d003-dddd-7000-8000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DateOfBirth = new DateTime(1985, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Nguyễn Văn Minh",
                            HireDate = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LicenseClass = "B2",
                            LicenseExpiry = new DateTime(2028, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LicenseNumber = "B2-123456",
                            PhoneNumber = "0901234567",
                            Status = 1,
                            TenantId = new Guid("0195c63a-727b-7f32-8e2d-3f4a5b6c7d8e")
                        },
                        new
                        {
                            DriverId = new Guid("0195d003-dddd-7000-8000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DateOfBirth = new DateTime(1980, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Trần Thanh Tùng",
                            HireDate = new DateTime(2019, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LicenseClass = "FC",
                            LicenseExpiry = new DateTime(2027, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LicenseNumber = "FC-234567",
                            PhoneNumber = "0912345678",
                            Status = 1,
                            TenantId = new Guid("0195c63a-727b-7f32-8e2d-3f4a5b6c7d8e")
                        },
                        new
                        {
                            DriverId = new Guid("0195d003-dddd-7000-8000-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DateOfBirth = new DateTime(1990, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Lê Văn Hùng",
                            HireDate = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LicenseClass = "C",
                            LicenseExpiry = new DateTime(2029, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LicenseNumber = "C-345678",
                            PhoneNumber = "0923456789",
                            Status = 1,
                            TenantId = new Guid("0195c63a-727b-7f32-8e2d-3f4a5b6c7d8e")
                        },
                        new
                        {
                            DriverId = new Guid("0195d003-dddd-7000-8000-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DateOfBirth = new DateTime(1978, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Phạm Quốc Bảo",
                            HireDate = new DateTime(2018, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LicenseClass = "D",
                            LicenseExpiry = new DateTime(2027, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LicenseNumber = "D-456789",
                            PhoneNumber = "0934567890",
                            Status = 1,
                            TenantId = new Guid("0195c63a-727b-7f32-8e2d-3f4a5b6c7d8e")
                        },
                        new
                        {
                            DriverId = new Guid("0195d003-dddd-7000-8000-000000000005"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DateOfBirth = new DateTime(1992, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Hoàng Văn Nam",
                            HireDate = new DateTime(2022, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LicenseClass = "C",
                            LicenseExpiry = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LicenseNumber = "C-567890",
                            Notes = "Bằng lái sắp hết hạn — cần gia hạn trước tháng 5/2026",
                            PhoneNumber = "0945678901",
                            Status = 1,
                            TenantId = new Guid("0195c63a-727b-7f32-8e2d-3f4a5b6c7d8e")
                        },
                        new
                        {
                            DriverId = new Guid("0195d003-dddd-7000-8000-000000000006"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DateOfBirth = new DateTime(1995, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Nguyễn Đức Trí",
                            HireDate = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LicenseClass = "B2",
                            LicenseExpiry = new DateTime(2030, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LicenseNumber = "B2-678901",
                            PhoneNumber = "0956789012",
                            Status = 2,
                            TenantId = new Guid("0195c63a-727b-7f32-8e2d-3f4a5b6c7d8e")
                        },
                        new
                        {
                            DriverId = new Guid("0195d003-dddd-7000-8000-000000000007"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DateOfBirth = new DateTime(1983, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Võ Minh Phúc",
                            HireDate = new DateTime(2017, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LicenseClass = "FC",
                            LicenseExpiry = new DateTime(2028, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LicenseNumber = "FC-789012",
                            PhoneNumber = "0967890123",
                            Status = 1,
                            TenantId = new Guid("0195c63a-727b-7f32-8e2d-3f4a5b6c7d8e")
                        },
                        new
                        {
                            DriverId = new Guid("0195d003-dddd-7000-8000-000000000008"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DateOfBirth = new DateTime(1988, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Đặng Văn Long",
                            HireDate = new DateTime(2016, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LicenseClass = "C",
                            LicenseExpiry = new DateTime(2027, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LicenseNumber = "C-890123",
                            PhoneNumber = "0978901234",
                            Status = 3,
                            TenantId = new Guid("0195c63a-727b-7f32-8e2d-3f4a5b6c7d8e")
                        });
                });

            modelBuilder.Entity("back_end_for_TMS.Models.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CargoDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("CargoWeightKg")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PickupAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("QuotedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("RequestedDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RequestedPickupDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "OrderNumber")
                        .IsUnique();

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = new Guid("0195d001-aaaa-7000-8000-000000000001"),
                            CargoDescription = "Nội thất gia đình — ghế sofa, bàn, ghế",
                            CargoWeightKg = 350m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerId = new Guid("0195d004-cccc-7000-8000-000000000001"),
                            DeliveryAddress = "456 Lê Lợi, Quận 3, Tp. Hồ Chí Minh",
                            Notes = "Customer requests morning pickup",
                            OrderNumber = "ORD-000001",
                            PickupAddress = "123 Nguyễn Huệ, Quận 1, Tp. Hồ Chí Minh",
                            QuotedPrice = 2500000m,
                            RequestedDeliveryDate = new DateTime(2026, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequestedPickupDate = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TenantId = new Guid("0195c63a-727b-7f32-8e2d-3f4a5b6c7d8e")
                        },
                        new
                        {
                            OrderId = new Guid("0195d001-aaaa-7000-8000-000000000002"),
                            CargoDescription = "Thiết bị văn phòng — bàn làm việc, màn hình, máy in",
                            CargoWeightKg = 500m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerId = new Guid("0195d004-cccc-7000-8000-000000000002"),
                            DeliveryAddress = "12 Phạm Văn Đồng, Thủ Đức, Tp. Hồ Chí Minh",
                            OrderNumber = "ORD-000002",
                            PickupAddress = "789 Trần Hưng Đạo, Quận 5, Tp. Hồ Chí Minh",
                            QuotedPrice = 4000000m,
                            RequestedDeliveryDate = new DateTime(2026, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequestedPickupDate = new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TenantId = new Guid("0195c63a-727b-7f32-8e2d-3f4a5b6c7d8e")
                        },
                        new
                        {
                            OrderId = new Guid("0195d001-aaaa-7000-8000-000000000003"),
                            CargoDescription = "Tủ lạnh và máy giặt",
                            CargoWeightKg = 200m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerId = new Guid("0195d004-cccc-7000-8000-000000000003"),
                            DeliveryAddress = "56 Nguyễn Văn Linh, Quận 7, Tp. Hồ Chí Minh",
                            OrderNumber = "ORD-000003",
                            PickupAddress = "34 Võ Văn Tần, Quận 3, Tp. Hồ Chí Minh",
                            QuotedPrice = 1800000m,
                            RequestedDeliveryDate = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequestedPickupDate = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            TenantId = new Guid("0195c63a-727b-7f32-8e2d-3f4a5b6c7d8e"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            OrderId = new Guid("0195d001-aaaa-7000-8000-000000000004"),
                            CargoDescription = "Hành lý cá nhân — hộp carton, quần áo, dụng cụ nhà bếp",
                            CargoWeightKg = 150m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerId = new Guid("0195d004-cccc-7000-8000-000000000004"),
                            DeliveryAddress = "90 Lê Văn Việt, Quận 9, Tp. Hồ Chí Minh",
                            OrderNumber = "ORD-000004",
                            PickupAddress = "78 Lý Tự Trọng, Quận 1, Tp. Hồ Chí Minh",
                            QuotedPrice = 1200000m,
                            RequestedDeliveryDate = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequestedPickupDate = new DateTime(2026, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            TenantId = new Guid("0195c63a-727b-7f32-8e2d-3f4a5b6c7d8e"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            OrderId = new Guid("0195d001-aaaa-7000-8000-000000000005"),
                            CargoDescription = "Vật liệu xây dựng — xi măng, thanh thép",
                            CargoWeightKg = 2000m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerId = new Guid("0195d004-cccc-7000-8000-000000000001"),
                            DeliveryAddress = "200 Quang Trung, Gò Vấp, Tp. Hồ Chí Minh",
                            OrderNumber = "ORD-000005",
                            PickupAddress = "100 Cách Mạng Tháng 8, Quận 10, Tp. Hồ Chí Minh",
                            QuotedPrice = 5500000m,
                            RequestedDeliveryDate = new DateTime(2026, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequestedPickupDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 4,
                            TenantId = new Guid("0195c63a-727b-7f32-8e2d-3f4a5b6c7d8e"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            OrderId = new Guid("0195d001-aaaa-7000-8000-000000000006"),
                            CargoDescription = "Điện tử gia dụng — TV, điều hòa không khí",
                            CargoWeightKg = 300m,
                            CompletedAt = new DateTimeOffset(new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomerId = new Guid("0195d004-cccc-7000-8000-000000000002"),
                            DeliveryAddress = "88 Nguyễn Thị Minh Khai, Quận 3, Tp. Hồ Chí Minh",
                            Notes = "Customer paid in full",
                            OrderNumber = "ORD-000006",
                            PickupAddress = "44 Hai Bà Trưng, Quận 1, Tp. Hồ Chí Minh",
                            QuotedPrice = 3200000m,
                            RequestedDeliveryDate = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequestedPickupDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 5,
                            TenantId = new Guid("0195c63a-727b-7f32-8e2d-3f4a5b6c7d8e"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("back_end_for_TMS.Models.Tenant", b =>
                {
                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TenantId");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            TenantId = new Guid("0195c63a-727b-7f32-8e2d-3f4a5b6c7d8e"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Alpha Logistics",
                            OwnerId = "u-admin"
                        },
                        new
                        {
                            TenantId = new Guid("0195c63a-727b-7f32-8e2d-3f4a5b6c7d8f"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Bravo Trans",
                            OwnerId = "u-user1"
                        },
                        new
                        {
                            TenantId = new Guid("0195c63a-727b-7f32-8e2d-3f4a5b6c7d90"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Charlie Freight",
                            OwnerId = "u-admin"
                        },
                        new
                        {
                            TenantId = new Guid("0195c63a-727b-7f32-8e2d-3f4a5b6c7d91"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Delta Moving",
                            OwnerId = "u-user1"
                        },
                        new
                        {
                            TenantId = new Guid("0195c63a-727b-7f32-8e2d-3f4a5b6c7d92"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Echo Shipping",
                            OwnerId = "u-admin"
                        });
                });

            modelBuilder.Entity("back_end_for_TMS.Models.Trip", b =>
                {
                    b.Property<Guid>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActualDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActualPickupDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CostNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("FuelCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("OtherCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PlannedDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PlannedPickupDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("TollCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TripNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TruckId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("TripId");

                    b.HasIndex("DriverId");

                    b.HasIndex("OrderId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TruckId");

                    b.HasIndex("TenantId", "TripNumber")
                        .IsUnique();

                    b.ToTable("Trips");

                    b.HasData(
                        new
                        {
                            TripId = new Guid("0195d002-bbbb-7000-8000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DriverId = new Guid("0195d003-dddd-7000-8000-000000000001"),
                            Notes = "Scheduled for morning pickup",
                            OrderId = new Guid("0195d001-aaaa-7000-8000-000000000003"),
                            PlannedDeliveryDate = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlannedPickupDate = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TenantId = new Guid("0195c63a-727b-7f32-8e2d-3f4a5b6c7d8e"),
                            TripNumber = "TRP-000001",
                            TruckId = new Guid("0195d005-eeee-7000-8000-000000000001")
                        },
                        new
                        {
                            TripId = new Guid("0195d002-bbbb-7000-8000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DriverId = new Guid("0195d003-dddd-7000-8000-000000000002"),
                            OrderId = new Guid("0195d001-aaaa-7000-8000-000000000004"),
                            PlannedDeliveryDate = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlannedPickupDate = new DateTime(2026, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TenantId = new Guid("0195c63a-727b-7f32-8e2d-3f4a5b6c7d8e"),
                            TripNumber = "TRP-000002",
                            TruckId = new Guid("0195d005-eeee-7000-8000-000000000002")
                        },
                        new
                        {
                            TripId = new Guid("0195d002-bbbb-7000-8000-000000000003"),
                            ActualDeliveryDate = new DateTime(2026, 3, 16, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            ActualPickupDate = new DateTime(2026, 3, 15, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            CompletedAt = new DateTimeOffset(new DateTime(2026, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CostNotes = "Highway toll + parking fee",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DriverId = new Guid("0195d003-dddd-7000-8000-000000000003"),
                            FuelCost = 850000m,
                            OrderId = new Guid("0195d001-aaaa-7000-8000-000000000005"),
                            OtherCost = 50000m,
                            PlannedDeliveryDate = new DateTime(2026, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlannedPickupDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 3,
                            TenantId = new Guid("0195c63a-727b-7f32-8e2d-3f4a5b6c7d8e"),
                            TollCost = 120000m,
                            TripNumber = "TRP-000003",
                            TruckId = new Guid("0195d005-eeee-7000-8000-000000000003"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            TripId = new Guid("0195d002-bbbb-7000-8000-000000000004"),
                            ActualDeliveryDate = new DateTime(2026, 3, 11, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ActualPickupDate = new DateTime(2026, 3, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            CompletedAt = new DateTimeOffset(new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DriverId = new Guid("0195d003-dddd-7000-8000-000000000004"),
                            FuelCost = 600000m,
                            OrderId = new Guid("0195d001-aaaa-7000-8000-000000000006"),
                            PlannedDeliveryDate = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlannedPickupDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 3,
                            TenantId = new Guid("0195c63a-727b-7f32-8e2d-3f4a5b6c7d8e"),
                            TollCost = 80000m,
                            TripNumber = "TRP-000004",
                            TruckId = new Guid("0195d005-eeee-7000-8000-000000000004"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            TripId = new Guid("0195d002-bbbb-7000-8000-000000000005"),
                            CancellationReason = "Truck broke down before pickup",
                            CancelledAt = new DateTimeOffset(new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DriverId = new Guid("0195d003-dddd-7000-8000-000000000005"),
                            OrderId = new Guid("0195d001-aaaa-7000-8000-000000000005"),
                            PlannedDeliveryDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlannedPickupDate = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 4,
                            TenantId = new Guid("0195c63a-727b-7f32-8e2d-3f4a5b6c7d8e"),
                            TripNumber = "TRP-000005",
                            TruckId = new Guid("0195d005-eeee-7000-8000-000000000005"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("back_end_for_TMS.Models.Truck", b =>
                {
                    b.Property<Guid>("TruckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("int");

                    b.Property<string>("EngineNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HeightMm")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastMaintenanceDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LengthMm")
                        .HasColumnType("int");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MaxPayloadKg")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ModelYear")
                        .HasColumnType("int");

                    b.Property<decimal>("OdometerReading")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OwnershipType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TruckType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("VinNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WidthMm")
                        .HasColumnType("int");

                    b.HasKey("TruckId");

                    b.HasIndex("TenantId");

                    b.ToTable("Trucks");

                    b.HasData(
                        new
                        {
                            TruckId = new Guid("0195d005-eeee-7000-8000-000000000001"),
                            Brand = "Hino",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentStatus = 1,
                            EngineNumber = "J08ETUA01234",
                            HeightMm = 2800,
                            LastMaintenanceDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthMm = 9600,
                            LicensePlate = "51C-123.45",
                            MaxPayloadKg = 8000m,
                            ModelYear = 2020,
                            OdometerReading = 85000m,
                            OwnershipType = 1,
                            PurchaseDate = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenantId = new Guid("0195c63a-727b-7f32-8e2d-3f4a5b6c7d8e"),
                            TruckType = "Thùng kín",
                            VinNumber = "JHLRE4H77BC001234",
                            WidthMm = 2490
                        },
                        new
                        {
                            TruckId = new Guid("0195d005-eeee-7000-8000-000000000002"),
                            Brand = "Isuzu",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentStatus = 1,
                            EngineNumber = "6HK1AUUA02345",
                            LastMaintenanceDate = new DateTime(2025, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthMm = 8200,
                            LicensePlate = "51C-234.56",
                            MaxPayloadKg = 7500m,
                            ModelYear = 2019,
                            OdometerReading = 120000m,
                            OwnershipType = 1,
                            PurchaseDate = new DateTime(2019, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenantId = new Guid("0195c63a-727b-7f32-8e2d-3f4a5b6c7d8e"),
                            TruckType = "Mui bạt",
                            VinNumber = "JAATV6512KA002345",
                            WidthMm = 2490
                        },
                        new
                        {
                            TruckId = new Guid("0195d005-eeee-7000-8000-000000000003"),
                            Brand = "Howo",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentStatus = 2,
                            EngineNumber = "WD615AUUA03456",
                            HeightMm = 3200,
                            LastMaintenanceDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthMm = 12000,
                            LicensePlate = "51D-345.67",
                            MaxPayloadKg = 15000m,
                            ModelYear = 2021,
                            OdometerReading = 65000m,
                            OwnershipType = 1,
                            PurchaseDate = new DateTime(2021, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenantId = new Guid("0195c63a-727b-7f32-8e2d-3f4a5b6c7d8e"),
                            TruckType = "Thùng kín",
                            VinNumber = "LZGAAHBN0M1003456",
                            WidthMm = 2550
                        },
                        new
                        {
                            TruckId = new Guid("0195d005-eeee-7000-8000-000000000004"),
                            Brand = "Volvo",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentStatus = 1,
                            EngineNumber = "D13KAUUA04567",
                            HeightMm = 3800,
                            LastMaintenanceDate = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthMm = 11500,
                            LicensePlate = "51D-456.78",
                            MaxPayloadKg = 20000m,
                            ModelYear = 2022,
                            OdometerReading = 40000m,
                            OwnershipType = 2,
                            PurchaseDate = new DateTime(2022, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenantId = new Guid("0195c63a-727b-7f32-8e2d-3f4a5b6c7d8e"),
                            TruckType = "Bồn",
                            VinNumber = "YV2R4A2A4NA004567",
                            WidthMm = 2550
                        },
                        new
                        {
                            TruckId = new Guid("0195d005-eeee-7000-8000-000000000005"),
                            Brand = "Scania",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentStatus = 3,
                            EngineNumber = "DC13AUUA05678",
                            LastMaintenanceDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthMm = 12000,
                            LicensePlate = "51C-567.89",
                            MaxPayloadKg = 18000m,
                            ModelYear = 2018,
                            OdometerReading = 210000m,
                            OwnershipType = 1,
                            PurchaseDate = new DateTime(2018, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenantId = new Guid("0195c63a-727b-7f32-8e2d-3f4a5b6c7d8e"),
                            TruckType = "Mui bạt",
                            VinNumber = "XLERX441XKA005678",
                            WidthMm = 2550
                        },
                        new
                        {
                            TruckId = new Guid("0195d005-eeee-7000-8000-000000000006"),
                            Brand = "Mercedes-Benz",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentStatus = 1,
                            EngineNumber = "OM471AUUA06789",
                            HeightMm = 3500,
                            LastMaintenanceDate = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthMm = 12000,
                            LicensePlate = "29H-678.90",
                            MaxPayloadKg = 25000m,
                            ModelYear = 2023,
                            OdometerReading = 18000m,
                            OwnershipType = 2,
                            PurchaseDate = new DateTime(2023, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenantId = new Guid("0195c63a-727b-7f32-8e2d-3f4a5b6c7d8e"),
                            TruckType = "Thùng kín",
                            VinNumber = "WDB96300312006789",
                            WidthMm = 2550
                        },
                        new
                        {
                            TruckId = new Guid("0195d005-eeee-7000-8000-000000000007"),
                            Brand = "Man",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentStatus = 1,
                            EngineNumber = "D2676AUUA07890",
                            HeightMm = 3600,
                            LastMaintenanceDate = new DateTime(2025, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthMm = 11000,
                            LicensePlate = "29H-789.01",
                            MaxPayloadKg = 22000m,
                            ModelYear = 2020,
                            OdometerReading = 92000m,
                            OwnershipType = 1,
                            PurchaseDate = new DateTime(2020, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenantId = new Guid("0195c63a-727b-7f32-8e2d-3f4a5b6c7d8e"),
                            TruckType = "Cẩu",
                            VinNumber = "WMA06XZZ0KM007890",
                            WidthMm = 2550
                        },
                        new
                        {
                            TruckId = new Guid("0195d005-eeee-7000-8000-000000000008"),
                            Brand = "Daf",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentStatus = 4,
                            EngineNumber = "MX13AUUA08901",
                            HeightMm = 3200,
                            LastMaintenanceDate = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthMm = 10500,
                            LicensePlate = "29C-890.12",
                            MaxPayloadKg = 30000m,
                            ModelYear = 2021,
                            OdometerReading = 155000m,
                            OwnershipType = 2,
                            PurchaseDate = new DateTime(2021, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenantId = new Guid("0195c63a-727b-7f32-8e2d-3f4a5b6c7d8e"),
                            TruckType = "Tự đổ",
                            VinNumber = "XLRTE45MS0E008901",
                            WidthMm = 2550
                        },
                        new
                        {
                            TruckId = new Guid("0195d005-eeee-7000-8000-000000000009"),
                            Brand = "Hino",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentStatus = 5,
                            EngineNumber = "J08ETUA09012",
                            LastMaintenanceDate = new DateTime(2025, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthMm = 9200,
                            LicensePlate = "43A-901.23",
                            MaxPayloadKg = 9000m,
                            ModelYear = 2019,
                            OdometerReading = 280000m,
                            OwnershipType = 1,
                            PurchaseDate = new DateTime(2019, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenantId = new Guid("0195c63a-727b-7f32-8e2d-3f4a5b6c7d8e"),
                            TruckType = "Mui bạt",
                            VinNumber = "JHLRE4H52KA009012",
                            WidthMm = 2490
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("back_end_for_TMS.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("back_end_for_TMS.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end_for_TMS.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("back_end_for_TMS.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("back_end_for_TMS.Models.AppUser", b =>
                {
                    b.HasOne("back_end_for_TMS.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("back_end_for_TMS.Models.Customer", b =>
                {
                    b.HasOne("back_end_for_TMS.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("back_end_for_TMS.Models.Driver", b =>
                {
                    b.HasOne("back_end_for_TMS.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("back_end_for_TMS.Models.Order", b =>
                {
                    b.HasOne("back_end_for_TMS.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("back_end_for_TMS.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("back_end_for_TMS.Models.Trip", b =>
                {
                    b.HasOne("back_end_for_TMS.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("back_end_for_TMS.Models.Order", "Order")
                        .WithMany("Trips")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end_for_TMS.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("back_end_for_TMS.Models.Truck", "Truck")
                        .WithMany()
                        .HasForeignKey("TruckId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Order");

                    b.Navigation("Truck");
                });

            modelBuilder.Entity("back_end_for_TMS.Models.Truck", b =>
                {
                    b.HasOne("back_end_for_TMS.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("back_end_for_TMS.Models.Order", b =>
                {
                    b.Navigation("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
