// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using back_end_for_TMS.Infrastructure.Database;

#nullable disable

namespace back_end_for_TMS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260314143846_Truck")]
    partial class Truck
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "r-admin",
                            ConcurrencyStamp = "STATIC_STAMP_123456",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "r-user",
                            ConcurrencyStamp = "STATIC_STAMP_123456",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "u-admin",
                            RoleId = "r-admin"
                        },
                        new
                        {
                            UserId = "u-user1",
                            RoleId = "r-user"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("back_end_for_TMS.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AppName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "u-admin",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "STATIC_STAMP_123456",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@asp.app",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ASP.APP",
                            NormalizedUserName = "TOP1SERVER",
                            PasswordHash = "AQAAAAIAAYagAAAAEOf6Pb8v/8VwLIDv8T6/7UfVvJqR9Z0X5Y6vX5Y6vX",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "STATIC_STAMP_123456",
                            TwoFactorEnabled = false,
                            UserName = "Top1Server"
                        },
                        new
                        {
                            Id = "u-user1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "STATIC_STAMP_123456",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user1@asp.app",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER1@ASP.APP",
                            NormalizedUserName = "USER1",
                            PasswordHash = "AQAAAAIAAYagAAAAEOf6Pb8v/8VwLIDv8T6/7UfVvJqR9Z0X5Y6vX5Y6vX",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "STATIC_STAMP_123456",
                            TwoFactorEnabled = false,
                            UserName = "User1"
                        });
                });

            modelBuilder.Entity("back_end_for_TMS.Models.Truck", b =>
                {
                    b.Property<Guid>("TruckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("int");

                    b.Property<string>("EngineNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HeightMm")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastMaintenanceDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LengthMm")
                        .HasColumnType("int");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("MaxPayloadKg")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ModelYear")
                        .HasColumnType("int");

                    b.Property<decimal>("OdometerReading")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OwnershipType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TruckType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("VinNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WidthMm")
                        .HasColumnType("int");

                    b.HasKey("TruckId");

                    b.HasIndex("LicensePlate")
                        .IsUnique();

                    b.ToTable("Trucks");

                    b.HasData(
                        new
                        {
                            TruckId = new Guid("c4889f9e-759c-efc3-070c-02ceb8cd064a"),
                            Brand = "Howo",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentStatus = 5,
                            EngineNumber = "0RZK45ET2Q1F",
                            HeightMm = 2531,
                            LastMaintenanceDate = new DateTime(2024, 11, 8, 5, 15, 31, 994, DateTimeKind.Unspecified).AddTicks(9268),
                            LengthMm = 7271,
                            LicensePlate = "2917-WJ65",
                            MaxPayloadKg = 14910.21m,
                            ModelYear = 2015,
                            OdometerReading = 69673.32m,
                            OwnershipType = 1,
                            PurchaseDate = new DateTime(2025, 10, 19, 16, 9, 53, 115, DateTimeKind.Unspecified).AddTicks(2034),
                            TruckType = "Cẩu",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VinNumber = "9GZ4DNTSWGWL93896",
                            WidthMm = 2557
                        },
                        new
                        {
                            TruckId = new Guid("3a5c6033-a167-8abb-9156-2d55bbd81297"),
                            Brand = "Isuzu",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentStatus = 4,
                            EngineNumber = "XSLI9KHOAOGI",
                            HeightMm = 3354,
                            LastMaintenanceDate = new DateTime(2026, 1, 11, 9, 1, 2, 593, DateTimeKind.Unspecified).AddTicks(7211),
                            LengthMm = 7837,
                            LicensePlate = "7448-YP20",
                            MaxPayloadKg = 19024.92m,
                            ModelYear = 2015,
                            OdometerReading = 419693.81m,
                            OwnershipType = 1,
                            PurchaseDate = new DateTime(2017, 3, 22, 6, 6, 49, 619, DateTimeKind.Unspecified).AddTicks(2731),
                            TruckType = "Cẩu",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VinNumber = "LR5H42KG7NI092672",
                            WidthMm = 2542
                        },
                        new
                        {
                            TruckId = new Guid("2df255c4-273c-da52-1071-9ed79e5f13e0"),
                            Brand = "Daf",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentStatus = 2,
                            EngineNumber = "65JQZKK27JHW",
                            HeightMm = 2595,
                            LastMaintenanceDate = new DateTime(2025, 6, 25, 7, 26, 30, 743, DateTimeKind.Unspecified).AddTicks(5736),
                            LengthMm = 10235,
                            LicensePlate = "1795-PY91",
                            MaxPayloadKg = 12589.03m,
                            ModelYear = 2018,
                            OdometerReading = 345576.58m,
                            OwnershipType = 1,
                            PurchaseDate = new DateTime(2019, 9, 7, 5, 38, 14, 623, DateTimeKind.Unspecified).AddTicks(5856),
                            TruckType = "Cẩu",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VinNumber = "1OSM8M5T9YNG92381",
                            WidthMm = 2474
                        },
                        new
                        {
                            TruckId = new Guid("d20513a0-3f37-4c43-ebb3-bbca0ca8bdb0"),
                            Brand = "Mercedes-Benz",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentStatus = 5,
                            EngineNumber = "ATQN5TNE4LRT",
                            HeightMm = 2716,
                            LastMaintenanceDate = new DateTime(2025, 10, 21, 21, 29, 16, 263, DateTimeKind.Unspecified).AddTicks(909),
                            LengthMm = 8943,
                            LicensePlate = "2093-BP36",
                            MaxPayloadKg = 17234.84m,
                            ModelYear = 2017,
                            OdometerReading = 129874.43m,
                            OwnershipType = 1,
                            PurchaseDate = new DateTime(2019, 2, 15, 12, 55, 23, 370, DateTimeKind.Unspecified).AddTicks(1670),
                            TruckType = "Cẩu",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VinNumber = "AI6X76CHTGFT55593",
                            WidthMm = 2405
                        },
                        new
                        {
                            TruckId = new Guid("08a20656-efdc-ce61-cf1f-e0cfb319623e"),
                            Brand = "Scania",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentStatus = 3,
                            EngineNumber = "CRBRZ130E4IC",
                            HeightMm = 3026,
                            LastMaintenanceDate = new DateTime(2025, 10, 5, 7, 45, 43, 232, DateTimeKind.Unspecified).AddTicks(8369),
                            LengthMm = 7197,
                            LicensePlate = "9376-E361",
                            MaxPayloadKg = 25695.97m,
                            ModelYear = 2020,
                            OdometerReading = 125867.50m,
                            OwnershipType = 2,
                            PurchaseDate = new DateTime(2024, 7, 14, 16, 40, 36, 809, DateTimeKind.Unspecified).AddTicks(6497),
                            TruckType = "Mui bạt",
                            VinNumber = "XNVAW6LCBKO098514",
                            WidthMm = 2553
                        },
                        new
                        {
                            TruckId = new Guid("617b43e9-052f-826b-454f-dd540671ba7f"),
                            Brand = "Volvo",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentStatus = 3,
                            EngineNumber = "9IZRW4X7MEVO",
                            HeightMm = 3334,
                            LastMaintenanceDate = new DateTime(2024, 10, 21, 11, 44, 2, 924, DateTimeKind.Unspecified).AddTicks(8649),
                            LengthMm = 5252,
                            LicensePlate = "5666-ID94",
                            MaxPayloadKg = 4558.34m,
                            ModelYear = 2018,
                            OdometerReading = 459416.72m,
                            OwnershipType = 1,
                            PurchaseDate = new DateTime(2022, 4, 15, 12, 3, 47, 86, DateTimeKind.Unspecified).AddTicks(7788),
                            TruckType = "Bồn",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VinNumber = "AMF2H9SHDSN471834",
                            WidthMm = 2544
                        },
                        new
                        {
                            TruckId = new Guid("1c7617df-b9c2-fa5a-3a7d-3f4b4bb7ee18"),
                            Brand = "Volvo",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentStatus = 5,
                            EngineNumber = "E5J1248ROIH9",
                            HeightMm = 3328,
                            LastMaintenanceDate = new DateTime(2024, 10, 26, 19, 22, 50, 806, DateTimeKind.Unspecified).AddTicks(7459),
                            LengthMm = 9892,
                            LicensePlate = "2965-KD11",
                            MaxPayloadKg = 23643.01m,
                            ModelYear = 2018,
                            OdometerReading = 195850.70m,
                            OwnershipType = 1,
                            PurchaseDate = new DateTime(2022, 2, 2, 12, 24, 39, 865, DateTimeKind.Unspecified).AddTicks(8222),
                            TruckType = "Mui bạt",
                            VinNumber = "WEZBRTAJULHJ86716",
                            WidthMm = 2424
                        },
                        new
                        {
                            TruckId = new Guid("4eb6cb58-dc2b-89b4-1223-5ae808fbfdbb"),
                            Brand = "Isuzu",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentStatus = 2,
                            EngineNumber = "G72MT8Q1ND57",
                            HeightMm = 2661,
                            LastMaintenanceDate = new DateTime(2025, 8, 7, 23, 51, 10, 902, DateTimeKind.Unspecified).AddTicks(2862),
                            LengthMm = 9169,
                            LicensePlate = "3108-VI14",
                            MaxPayloadKg = 23866.81m,
                            ModelYear = 2020,
                            OdometerReading = 229930.14m,
                            OwnershipType = 1,
                            PurchaseDate = new DateTime(2019, 2, 27, 0, 45, 11, 257, DateTimeKind.Unspecified).AddTicks(4336),
                            TruckType = "Cẩu",
                            VinNumber = "CHV52V6QTKUV78068",
                            WidthMm = 2499
                        },
                        new
                        {
                            TruckId = new Guid("af57e96b-cbd7-e3f1-de60-408edf3ff3fd"),
                            Brand = "Isuzu",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentStatus = 5,
                            EngineNumber = "1T5IPYOV9UHM",
                            HeightMm = 3045,
                            LastMaintenanceDate = new DateTime(2025, 12, 21, 15, 9, 19, 279, DateTimeKind.Unspecified).AddTicks(6312),
                            LengthMm = 8840,
                            LicensePlate = "7310-3Q96",
                            MaxPayloadKg = 8310.22m,
                            ModelYear = 2016,
                            OdometerReading = 39006.62m,
                            OwnershipType = 1,
                            PurchaseDate = new DateTime(2017, 10, 11, 7, 38, 22, 846, DateTimeKind.Unspecified).AddTicks(3298),
                            TruckType = "Mui bạt",
                            VinNumber = "XCH11ZAPJ7TS67845",
                            WidthMm = 2468
                        },
                        new
                        {
                            TruckId = new Guid("40b25403-8b4a-d9de-148e-cf8707e18517"),
                            Brand = "Mercedes-Benz",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentStatus = 5,
                            EngineNumber = "SKH9XD1C5SZR",
                            HeightMm = 2613,
                            LastMaintenanceDate = new DateTime(2024, 9, 12, 5, 5, 53, 19, DateTimeKind.Unspecified).AddTicks(5515),
                            LengthMm = 6198,
                            LicensePlate = "7061-IZ47",
                            MaxPayloadKg = 27952.52m,
                            ModelYear = 2020,
                            OdometerReading = 308775.86m,
                            OwnershipType = 1,
                            PurchaseDate = new DateTime(2024, 3, 1, 19, 29, 37, 763, DateTimeKind.Unspecified).AddTicks(4202),
                            TruckType = "Bồn",
                            VinNumber = "WTGBCOF8M6T213769",
                            WidthMm = 2512
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("back_end_for_TMS.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("back_end_for_TMS.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end_for_TMS.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("back_end_for_TMS.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
